name: CI Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build artifacts and release
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Tachidesk
        uses: actions/checkout@v2
        with:
          repository: 'Suwayomi/Tachidesk'
          ref: master
          path: tachidesk
          fetch-depth: 0

      - name: Remove Tachidesk's webUI
        run: rm -rf tachidesk/webUI/src/*

      - name: Checkout Equinox and put it as webUI
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: tachidesk/webUI/src

# Build Tachidesk with Equinox together
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy CI gradle.properties
        run: |
          cd tachidesk
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Download android.jar
        run: |
          cd tachidesk
          curl https://raw.githubusercontent.com/Suwayomi/Tachidesk/android-jar/android.jar -o AndroidCompat/lib/android.jar

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/webUI/src/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/webUI/src/node_modules') }}

      - name: Build and copy webUI, Build Jar
        uses: eskatos/gradle-command-action@v1
        env:
          TachideskBuildType: "Stable"
        with:
          build-root-directory: tachidesk
          wrapper-directory: tachidesk
          arguments: :webUI:copyBuild :server:shadowJar --stacktrace
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: make windows packages
        run: |
          cd tachidesk/scripts
          ./windows-bundler.sh win32
          ./windows-bundler.sh win64

      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: "tachidesk/server/build/*.jar;tachidesk/server/build/*.zip"
          tags: true
          draft: true
          verbose: true
